services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: pdf_reader
  #   volumes:
  #     - .:/app
  #     - /app/.venv
  #   ports:
  #     - "8000:8000"
  #   # depends_on:
  #   #   - qdrant
  #   command: ["make", "dev"]

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
