version: 1
disable_existing_loggers: False

formatters:
  color:
    (): logger.formatter.CustomFormatter
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s (%(filename)s:%(lineno)d)"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: color
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: WARNING
    formatter: standard
    filename: logs/app.log
    mode: a

loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: False

  uvicorn.error:
    level: INFO
    handlers: [console, file]
    propagate: False

  uvicorn.access:
    level: INFO
    handlers: [console, file]
    propagate: False

  fastapi:
    level: INFO
    handlers: [console, file]
    propagate: False

root:
  level: DEBUG
  handlers: [console, file]
